export const AppRoutes = {
  home: "/",
  login: "/login",
  register: "/register",
  forgot_password: "/forgot-password",
  reset_password: "/reset-password",
  feed: "/feed",
  chat: "/chat",
  notifications: "/notifications",
  top_influencers: "/top-influencers",
  create_collection: "/create-collection",
  staking_pack: "/staking-pack",
  network_rewards: "/network-rewards",
  buy_ntr_dao: "/buy-ntr-dao",
  profits_dashboard: "/profits-dashboard",
  voting_chain: "/voting-chain",
  referral_program: "/referral-program",
} as const;
