version: "3"

services:
  service-development:
    network_mode: host
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: service-development
    volumes:
      - ../../:/app
      - /app/node_modules
