version: "3"

services:
  app-centher-io-development:
    container_name: app-centher-io
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: app-centher-io-development
    volumes:
      - ../../:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - centher-io

networks:
  centher-io:
    name: centher-io
    driver: bridge
