version: "3"

services:
  dapp-369x-io-development:
    container_name: dapp-369x-io
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: dapp-369x-io-development
    volumes:
      - ../../:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - 369x-io

networks:
  369x-io:
    name: 369x-io
    driver: bridge
