export enum QueryNames {
  GET_PRESALES = "GET_PRESALES",
  GET_PRESALE = "GET_PRESALE",
  GET_CLAIMABLE_REF_REWARDS = "GET_CLAIMABLE_REF_REWARDS",
  GET_CLAIMED_REF_REWARDS = "GET_CLAIMED_REF_REWARDS",
}
