import { User } from "@/hooks/stream/interfaces";

export enum CentalkUserStatusEnum {
  ONLINE = "ONLINE",
  OFFLINE = "OFFLINE",
}

export enum CentalkUserRoleEnum {
  HOST = "HOST",
  LISTENER = "LISTENER",
  SPEAKER = "SPEAKER",
}

export enum StreamSubscriptionEnum {
  SUBSCRIBE_ALL = "SUBSCRIBE_ALL",
  SUBSCRIBE_MESSAGE = "SUBSCRIBE_MESSAGE",
  SUBSCRIBE_SPEAKERS = "SUBSCRIBE_SPEAKERS",
  SUBSCRIBE_CURRENT_USER = "SUBSCRIBE_CURRENT_USER",
  SUBSCRIBE_HAS_TALK_REQUEST_USERS = "SUBSCRIBE_HAS_TALK_REQUEST_USERS",
  SUBSCRIBE_CURRENT_STREAM = "SUBSCRIBE_CURRENT_STREAM",
}

export interface ICentalkUser {
  id: string;
  name: string;
  image: string;
  isVerified?: boolean;
  isMuted?: boolean;
  isChatPermission?: boolean;
  status?: CentalkUserStatusEnum;
  role?: CentalkUserRoleEnum;
  hasTalkRequest: boolean;
}

export interface ICentalkMessage {
  createdAt: Date;
  content: string;
  id: string;
  sender: Partial<User>;
}

export enum StreamEventEnum {
  ON_STREAM_CONNECTED = "ON_STREAM_CONNECTED",
  ON_NEED_WALLET_LIST = "ON_NEED_WALLET_LIST",
  ON_NEED_BUY = "ON_NEED_BUY",
  ON_NEED_SWAP = "ON_NEED_SWAP",
  ON_NEED_PASSCODE = "ON_NEED_PASSCODE",
  ON_NEED_TOKEN_LIST = "ON_NEED_TOKEN_LIST",
  ON_COMPLETE_SET_PASSCODE = "ON_COMPLETE_SET_PASSCODE",
  ON_CLICK_BACK_BUTTON = "ON_CLICK_BACK_BUTTON",
  ON_NEED_TOKEN_DETAIL = "ON_NEED_TOKEN_DETAIL",
  ON_NEED_TOKEN_RECEIVE = "ON_NEED_TOKEN_RECEIVE",
  ON_NEED_SEND_TOKEN = "ON_NEED_SEND_TOKEN",
  ON_NEED_REFRESH = "ON_NEED_REFRESH",
  ON_COMPLETE_QRCODE_SCANNER = "ON_COMPLETE_QRCODE_SCANNER",
  ON_NEED_QRCODE_SCANNER = "ON_NEED_QRCODE_SCANNER",
  ON_NEED_STOP_QRCODE_SCANNER = "ON_NEED_STOP_QRCODE_SCANNER",
  ON_SELECT_TOKEN_IN_SWAP = "ON_SELECT_TOKEN_IN_SWAP",
  ON_NEED_CREDIT_CARD_LIST = "ON_NEED_CREDIT_CARD_LIST",
  ON_NEED_NETWORK_SUGGESTION_PEOPLE = "ON_NEED_NETWORK_SUGGESTION_PEOPLE",
  ON_NEED_NETWORK_NOTIFICATION_LIST = "ON_NEED_NETWORK_NOTIFICATION_LIST",
  ON_NEED_NETWORK_CONNECTION_LIST = "ON_NEED_NETWORK_CONNECTION_LIST",
  ON_NEED_NETWORK_SEARCH = "ON_NEED_NETWORK_SEARCH",
  ON_SELECT_CARD_IN_LIST = "ON_SELECT_CARD_IN_LIST",
  ON_SCROLL = "ON_SCROLL",
  ON_DONE_SEND_TRANSACTION = "ON_DONE_SEND_TRANSACTION",
  ON_NEED_STREAM_ACCESS = "ON_NEED_STREAM_ACCESS",
  ON_GET_STREAMS = "ON_GET_STREAMS",
  ON_GOTO_STREAM = "ON_GOTO_STREAM",
  ON_NEED_STREAM_TABS = "ON_NEED_STREAM_TABS",
  ON_UPDATE_AMA_SPEAKERS = "ON_UPDATE_AMA_SPEAKERS",
  ON_GET_NEW_STREAM_MESSAGE = "ON_GET_NEW_STREAM_MESSAGE",
  ON_FINISH_BROADCAST = "ON_FINISH_BROADCAST",
  ON_USER_KICKED = "ON_USER_KICKED",
  ON_CLOSE_STREAM_TABS_DIALOG = "ON_CLOSE_STREAM_TABS_DIALOG",
  ON_UPDATE_STREAM_CURRENT_USER = "ON_UPDATE_STREAM_CURRENT_USER",
  ON_UPDATE_STREAM_HAS_TALK_USERS = "ON_UPDATE_STREAM_HAS_TALK_USERS",
  ON_UPDATE_CONSUMER = "ON_UPDATE_CONSUMER",
  ON_UPDATE_VIDEO_STREAM = "ON_UPDATE_VIDEO_STREAM",
  ON_NEED_SEE_PROFIE = "ON_NEED_SEE_PROFIE",
  ON_NEED_CLOSE_PROFILE = "ON_NEED_CLOSE_PROFILE",
  ON_NEED_PROFILE_SETTINGS = "ON_NEED_PROFILE_SETTINGS",
  ON_NEED_EDIT_PROFILE = "ON_NEED_EDIT_PROFILE",
  ON_NEED_PROFILE_TEAM_MEMBERS = "ON_NEED_PROFILE_TEAM_MEMBERS",
  ON_NEED_PROFILE_SOCIAL_LINKS = "ON_NEED_PROFILE_SOCIAL_LINKS",
  ON_NEED_PROFILE_MENTIONS_AND_TAGS = "ON_NEED_PROFILE_MENTIONS_AND_TAGS",
  ON_NEED_SEE_COMMUNITY = "ON_NEED_SEE_COMMUNITY",
  ON_NEED_CREATE_POST = "ON_NEED_CREATE_POST",
  ON_NEED_POST_DETAILS = "ON_NEED_POST_DETAILS",
  ON_CREATE_CENTALK = "ON_CREATE_CENTALK",
  ON_NEED_OPEN_COMING_SOON_DIALOG = "ON_NEED_OPEN_COMING_SOON_DIALOG",
  ON_EDIT_PROFILE_DIALOG_CLOSING = "ON_EDIT_PROFILE_DIALOG_CLOSING",
  ON_GET_CURRENT_STREAM = "ON_GET_CURRENT_STREAM",
  ON_USER_DISCONNECTED_FROM_TALK = "ON_USER_DISCONNECTED_FROM_TALK",
  STREAM_INITIALIZATION_ERROR = "STREAM_INITIALIZATION_ERROR",
  ON_JOINED_TO_BROADCAST = "ON_JOINED_TO_BROADCAST",
  ON_NEED_TO_TRY_AGAIN = "ON_NEED_TO_TRY_AGAIN",
}
