export enum SmartContractName {
  CENTHER_TOKEN = "CENTHER_TOKEN",
  REGISTRATION = "REGISTRATION",
  PRESALE = "PRESALE",
  MARKETPALCE = "MARKETPALCE",
  MULTICALL = "MULTICALL",
  PANCAKE_ROUTER = "PANCAKE_ROUTER",
  WBNB = "WBNB",
  BUSD = "BUSD",
  NTR = "NTR",
  NATIVE_COLLECTION = "NATIVE_COLLECTION",
}
