export enum StreamSubscriptionEnum {
  SUBSCRIBE_ALL = "SUBSCRIBE_ALL",
  SUBSCRIBE_MESSAGE = "SUBSCRIBE_MESSAGE",
  SUBSCRIBE_SPEAKERS = "SUBSCRIBE_SPEAKERS",
  SUBSCRIBE_CURRENT_USER = "SUBSCRIBE_CURRENT_USER",
  SUBSCRIBE_HAS_TALK_REQUEST_USERS = "SUBSCRIBE_HAS_TALK_REQUEST_USERS",
  SUBSCRIBE_CURRENT_STREAM = "SUBSCRIBE_CURRENT_STREAM",
}
