export enum QueryNames {
  GET_PROJECTS = "GET_PROJECTS",
  GET_PROJECT = "GET_PROJECT",
  GET_USER_TRANSFERS_BY_POOL = "GET_USER_TRANSFERS_BY_POOL",
  GET_USER_CLAIMED_REWARDS = "GET_USER_CLAIMED_REWARDS",
  GET_USER_TOTAL_CLAIMED_REF_REWARDS = "GET_USER_TOTAL_CLAIMED_REF_REWARDS",
  GET_USER_CLAIMED_REF_REWARDS = "GET_USER_CLAIMED_REF_REWARDS",
  GET_USER_REFERRALS = "GET_USER_REFERRALS",
}
