apiVersion: v1
kind: Service
metadata:
  name: app-centher-io-cluster-ip-service
  namespace: centher-io-nsp
spec:
  type: ClusterIP
  selector:
    serviceName: app-centher-io-service-name
  ports:
    - port: 80
      targetPort: 3000