export const rooms = [
  {
    image: "/images/voispace.dummy.profile.png",
    live: true,
    eventName: "voispace",
  },
  {
    image: "/images/voispace.dummy.profile.png",
    live: false,
    eventName: "voispace",
  },
  {
    image: "/images/voispace.dummy.profile.png",
    live: false,
    eventName: "voispace",
  },
  {
    image: "/images/voispace.dummy.profile.png",
    live: false,
    eventName: "voispace",
  },
  {
    image: "/images/voispace.dummy.profile.png",
    live: false,
    eventName: "voispace",
  },
  {
    image: "/images/voispace.dummy.profile.png",
    live: false,
    eventName: "voispace",
  },
  {
    image: "/images/voispace.dummy.profile.png",
    live: false,
    eventName: "voispace",
  },
];

export const dummyAMAChannels = [
  {
    id: 1,
    name: "AMA Channel 1",
    description: "Description for AMA 1",
    views: 100,
    duration: "1h 30m",
  },
  {
    id: 2,
    name: "AMA Channel 2",
    description: "Description for AMA 2",
    views: 50,
    duration: "45m",
  },
  {
    id: 1,
    name: "AMA Channel 1",
    description: "Description for AMA 1",
    views: 100,
    duration: "1h 30m",
  },
  {
    id: 2,
    name: "AMA Channel 2",
    description: "Description for AMA 2",
    views: 50,
    duration: "45m",
  },
  {
    id: 1,
    name: "AMA Channel 1",
    description: "Description for AMA 1",
    views: 100,
    duration: "1h 30m",
  },
  {
    id: 2,
    name: "AMA Channel 2",
    description: "Description for AMA 2",
    views: 50,
    duration: "45m",
  },
  {
    id: 1,
    name: "AMA Channel 1",
    description: "Description for AMA 1",
    views: 100,
    duration: "1h 30m",
  },
  {
    id: 2,
    name: "AMA Channel 2",
    description: "Description for AMA 2",
    views: 50,
    duration: "45m",
  },
  {
    id: 1,
    name: "AMA Channel 1",
    description: "Description for AMA 1",
    views: 100,
    duration: "1h 30m",
  },
  {
    id: 2,
    name: "AMA Channel 2",
    description: "Description for AMA 2",
    views: 50,
    duration: "45m",
  },
  {
    id: 1,
    name: "AMA Channel 1",
    description: "Description for AMA 1",
    views: 100,
    duration: "1h 30m",
  },
  {
    id: 2,
    name: "AMA Channel 2",
    description: "Description for AMA 2",
    views: 50,
    duration: "45m",
  },
];

export const dummyLiveChannels = [
  {
    id: 1,
    name: "Live Channel 1",
    description: "Description for Live 1",
    views: 200,
    duration: "2h",
  },
  {
    id: 2,
    name: "Live Channel 2",
    description: "Description for Live 2",
    views: 150,
    duration: "1h 15m",
  },
  {
    id: 1,
    name: "Live Channel 1",
    description: "Description for Live 1",
    views: 200,
    duration: "2h",
  },
  {
    id: 2,
    name: "Live Channel 2",
    description: "Description for Live 2",
    views: 150,
    duration: "1h 15m",
  },
  {
    id: 1,
    name: "Live Channel 1",
    description: "Description for Live 1",
    views: 200,
    duration: "2h",
  },
  {
    id: 2,
    name: "Live Channel 2",
    description: "Description for Live 2",
    views: 150,
    duration: "1h 15m",
  },
  {
    id: 1,
    name: "Live Channel 1",
    description: "Description for Live 1",
    views: 200,
    duration: "2h",
  },
  {
    id: 2,
    name: "Live Channel 2",
    description: "Description for Live 2",
    views: 150,
    duration: "1h 15m",
  },
];
