export const speakers = [
  {
    name: "John Wedson",
    imageURL: "/images/profiles/Profile-0.svg",
    isSpeaking: false,
    isApproved: true,
    position: "Host",
  },
  {
    name: "John Wedson",
    imageURL: "/images/profiles/Profile-1.svg",
    isSpeaking: true,
    isApproved: true,
    position: "Speakers",
  },
  {
    name: "John Wedson",
    imageURL: "/images/profiles/Profile-2.svg",
    isSpeaking: false,
    isApproved: true,
    position: "Speakers",
  },
  {
    name: "John Wedson",
    imageURL: "/images/profiles/Profile-3.svg",
    isSpeaking: false,
    isApproved: true,
    position: "Speakers",
  },
  {
    name: "John Wedson",
    imageURL: "/images/profiles/Profile-4.svg",
    isSpeaking: false,
    isApproved: true,
    position: "Speakers",
  },
  {
    name: "John Wedson",
    imageURL: "/images/profiles/Profile-5.svg",
    isSpeaking: false,
    isApproved: true,
    position: "Speakers",
  },
  {
    name: "John Wedson",
    imageURL: "/images/profiles/Profile-6.svg",
    isSpeaking: true,
    isApproved: true,
    position: "Speakers",
  },
  {
    name: "John Wedson",
    imageURL: "/images/profiles/Profile-7.svg",
    isSpeaking: false,
    isApproved: true,
    position: "Speakers",
  },
  {
    name: "John Wedson",
    imageURL: "/images/profiles/Profile-8.svg",
    isSpeaking: false,
    isApproved: true,
    position: "Speakers",
  },
];
